spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: "jdbc:mysql://localhost:3306/chat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
spring.datasource.username: root
spring.datasource.password: as07091982
spring.freemarker.expose-request-attributes: true