spring.jpa.hibernate.ddl-auto: create
spring.datasource.url:
  "jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf8"
spring.datasource.username: root
spring.datasource.password: as07091982
spring.freemarker.expose-request-attributes: true